#!/bin/sh
if [ -z "$1" ]
then
  echo "Which folder do you want to deploy to GitHub Pages?"
  exit 1
fi

npm run build:prod
git add $1
git commit -m "$2"
git push origin master
git subtree push --prefix $1 origin gh-pages
printf '\nDeploy: Demo deployed to gh-pages\n'
